name: update docker on WEB_SERVER
on:
  push:
    branches:    
      - master  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEB_SERVER }}
        username: ${{ secrets.WEB_SERVER_USERNAME }}
        password: ${{ secrets.WEB_SERVER_PASSWORD }}
        port: ${{ secrets.WEB_SERVER_PORT }}
        script: |
          cd webapp 
          git pull
          yarn build
          docker-compose -f docker-compose-prod.yml up -d --build --force-recreate